[project]
name = "inferenceoptimization-ssd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "huggingface-hub>=0.31.2",
    "matplotlib>=3.10.3",
    "skypilot>=0.8.1",
]
